#version 450
#extension GL_EXT_shader_image_load_formatted : require

layout(local_size_x = 1, local_size_y = 1) in;
layout(set = 0, binding = 0) readonly uniform uimage2D source;
layout(set = 0, binding = 1, std430) writeonly buffer Output {
   uint values[];
} output_data;

void main()
{
   uvec2 position = gl_GlobalInvocationID.xy;
   uint linear_index = position.y * 17u + position.x;
   output_data.values[linear_index] = imageLoad(source, ivec2(position)).x;
}
