#version 450

layout(local_size_x = 8, local_size_y = 8) in;
layout(constant_id = 0) const uint test_width = 17u;
layout(constant_id = 1) const uint test_height = 13u;

layout(set = 0, binding = 0, rg16f) uniform readonly image2D source;
layout(set = 0, binding = 1, std430) writeonly buffer Output {
   vec2 values[];
} output_data;

void
main()
{
   uvec2 position = gl_GlobalInvocationID.xy;
   uvec2 size = uvec2(test_width, test_height);
   if (any(greaterThanEqual(position, size)))
      return;
   uint linear_index = position.y * size.x + position.x;
   output_data.values[linear_index] = imageLoad(source, ivec2(position)).xy;
}
