#version 450

layout(local_size_x = 8, local_size_y = 8) in;
layout(constant_id = 0) const uint test_width = 17u;
layout(constant_id = 1) const uint test_height = 13u;
layout(set = 0, binding = 0) writeonly uniform image2D destination;

shared vec4 shared_values[64];

void main()
{
   uvec2 position = gl_GlobalInvocationID.xy;
   uvec2 size = uvec2(test_width, test_height);
   if (any(greaterThanEqual(position, size)))
      return;
   uint i = position.y * size.x + position.x;
   vec4 value = vec4(float((i >> 0u) & 1u), float((i >> 1u) & 1u),
                     float((i >> 2u) & 1u), 1.0);
   uint local_index = gl_LocalInvocationIndex;
   shared_values[local_index] = value;
   barrier();
   value = shared_values[local_index];
   barrier();
   imageStore(destination, ivec2(position), value);
}
